# Generated by Django 3.2.14 on 2023-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('repita_clave', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('repita_email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('Petshop', 'Petshop'), ('Veterinaria', 'Veterinaria'), ('Hoteles', 'Hoteles'), ('Paseadores', 'Paseadores'), ('Cuidadores', 'Cuidadores'), ('Atencion 24 horas', 'Atencion 24 horas'), ('Mayoristas', 'Mayoristas')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('repita_clave', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('repita_email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Pez', 'Pez'), ('Tortuga', 'Tortuga'), ('Ave', 'Ave'), ('Reptil', 'Reptil'), ('Roedor', 'Roedor')], max_length=100)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'), ('Tucumán', 'Tucumán')], max_length=100)),
            ],
        ),
    ]
